# Declare Name of kernel module
KMOD = ng_regexec

# Enumerate Source files for kernel module
SRCS = ng_regexec.c regcomp.c regerror.c regexec.c regfree.c

# Include kernel module makefile
.include <bsd.kmod.mk>

